### ISSUE TITLE
Error while trying to stringify a BigInt

### ISSUE THREAD

**Issue by chikof** [RichardX366/prisma-cache#1]
You will have problems with the following line, well I had problems with it.
https://github.com/RichardX366/prisma-cache/blob/a365f0baeb7695fca1671b554aeadb8fd1ef1f41/index.js#L12

At the moment of [stringify] a [BigInt] it will throw an error because you cannot stringify a BigInt.
Prisma provides a solution to that in their docs, [take a look](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields#serializing-bigint).

[bigint]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
[stringify]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

**Comment by RichardX366** [comment]
Fixed, thanks for letting me know!
